### ISSUE TITLE
Bug in if no [M+H]+ or [M]+ is prioritized in the dataset

### ISSUE THREAD

**Issue by chufz** [kruvelab/MS2Quant#6]
Dear Helen,

i am not sure if you are already aware of it, but in the current code, if there is no [M+H]+ or [M]+ with the highest sirius score for one of all predicted compounds, there will be no prediction for all compounds, because of an error (I assume the vector sizes are not similar). Can you handle this through an if() function, that at least the rest of the compounds will be reported through a working predict function?

We will currently use a code to make sure and filter for compounds with M+H+/M+ in the highest sirius rank to reveal an output

**Comment by helensepman** [comment]
Hi Caroline, 
I appreciate the feedback, and apologies for the wait! I have implemented a fix now, but please let me know if you come across the same problem.
